export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const ADD_TO_CART='ADD_TO_CART';
export const DELETE_ITEM='DELETE_ITEM';
export const FILTER_ITEM='FILTER_ITEM';
export const FILTER_PRODUCTS='FILTER_PRODUCTS';